repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: frontend-lint
        name: frontend-lint
        entry: bash -c 'cd frontend && npm run format && npm run lint'
        language: system
        types_or: [ts, tsx]
        pass_filenames: false
        files: ^frontend/
