"""Initial schema: agent sessions and events

Revision ID: 282124c5ca1a
Revises: 
Create Date: 2026-03-29 18:23:17.223327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282124c5ca1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_ticket_id'), 'agent_sessions', ['ticket_id'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.Enum('AGENT_STARTED', 'AGENT_COMPLETED', 'AGENT_FAILED', 'TOOL_CALL', 'STATE_CHANGE', 'LOG', name='eventtype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_events_session_id', 'agent_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_events_session_id', table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_agent_sessions_ticket_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
